name: ✨ Feature Request
description: Suggest a new feature or improvement
title: "✨ [Feature]: "
labels: ["enhancement", "needs-triage"]
assignees: ["nazruden"]

body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a new feature! 🚀

  - type: checkboxes
    id: terms
    attributes:
      label: Pre-flight checklist
      description: Please check these items before submitting
      options:
        - label: I have searched for existing feature requests
          required: true
        - label: This feature doesn't exist in the current version
          required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem description
      description: Is your feature request related to a problem?
      placeholder: I'm always frustrated when...

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: Describe the solution you'd like to see
      placeholder: I would like to see...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Considered alternatives
      description: Describe any alternative solutions you've considered
      placeholder: Alternative approaches could be...

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would improve workflow
        - High - Blocking current work
        - Critical - Cannot proceed without this
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Any other context, mockups, or examples